development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: sim_messages_production

test:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: sim_messages_production

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: sim_messages_production
